---
- hosts: all
  tasks:
    - name: Install k9s
      ansible.builtin.includ_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'k9s version'
      ansible.builtin.command: /usr/local/bin/k9s version
      register: k9s_test_output
    - name: Output from 'k9s version'
      ansible.builtin.debug:
        msg: '{{ k9s_test_output.stdout }}'
